feat: Updated Config ZSHRC
Serginho/DotFiles pull request #2
Opened 2022-04-03 16:50 UTC by fabianlema

- Separate functions to another file
- Separate alias to another file
- Separate environment variables to .zshenv
- More iterm themes
- Iterm flema config
- Removed .DS_Store file

2022-04-24 12:16 UTC, Serginho requested changes
Revisado, documentei con comentario todo o que me interesa mergear.

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.functions
> +}
Eu esto sacaríao a un plugin en `ohmyzshcustom/plugins/images/`

Se usas squoosh habería que añadir ó readme como instalar squoosh, ou que depende de npx, eu poñería `npm install -g @squoosh/cli` e facería varias funcións:

- convert_webp
- convert_png
- convert_jpg

E que a cada un destes lle poidas pasar unha image, ou un directorio, e se lle pasas o directorio convirte todas.

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.functions
> +}
Este está vez pero tamén sacaríao a outro plugin de compress.

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.aliases
> +
Esto, podemos eliminar a parte que non é de mac. e quedarnos solo ca línea 

`export LSCOLORS=ExfxbEaEBxxEhEhBaDaCaD`

Porque na versión actual está posto bat, e xa movin eso

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.aliases
> +alias sortnr='sort -n -r'
Esto interesame ✅

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.aliases
> +alias vim='nvim'
Esto interesame ✅

2022-04-24 12:16 UTC, Serginho commented on ohmyzsh-custom/.aliases
> +alias merge-staging-master='git co master && git merge staging && git p && git co staging'
Esto xa está movido a work.plugin.zsh

2022-04-24 12:16 UTC, Serginho commented on .zshenv
> +export PUPPETEER_EXECUTABLE_PATH=`which chromium`
Este archivo todo 🆗 , quitaría o path `usr/local/games`

2022-04-24 12:16 UTC, Serginho commented on .gitignore
> +.DS_Store
💯  Interesame

2022-04-24 12:16 UTC, Serginho commented on .zshenv
> +export PUPPETEER_EXECUTABLE_PATH=`which chromium`
Añadir no readme o symbolic link a .zshenv

2022-04-24 12:16 UTC, Serginho commented on .zshrc
> +source $ZSH_CUSTOM/.aliases
Eu este no metería dentro de ohmyzsh porque me parece que son alias como moi genéricos, aquí solo metería alias tipo `alias rm='rm -i'` ou cousas así moi básicas. 
O archivo para eso tan genérico crearíao o lado de `.zshenv`, por ejemplo, `.zshaliases`

2022-04-24 12:16 UTC, Serginho commented on iterm-themes/Gruvbox Dark.itermcolors
> +<?xml version="1.0" encoding="UTF-8"?>
Este interesame.

Crearía unha carpeta `iterm` e dentro movería o `com.googlecode.iterm2-fl.plist` e crearía unha carpeta `themes`. Ainda que creo que o com.googlecode... moveríao eu porque parece que xa cambiou. xD

2022-05-18 17:57 UTC, fabianlema commented
Feitos os cambios. Engadido novo iterm color https://github.com/sindresorhus/iterm2-snazzy
Actualicei o README para ter en conta a instalación do PlugInstall que cando é unha instalación nova non o tes.

2022-07-18 21:57 UTC, closed without merging